server:
    port: 9001

spring:
    application:
        name: product-srv

eureka:
    client:
        register-with-eureka: true
        fetchRegistry: true
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #\u96C6\u7FA4\u7248

